### ISSUE TITLE
Having a hard time getting rector init-generate work on PHP8.1

### ISSUE THREAD

**Issue by wernerkrauss** [rectorphp/rector-generator#13]
Hi, 

I can't get `rector init-generate` to work, I guess I'm missing some dependencies.

`rector-generate` doesn't seem to work with `rector/rector`, and with `rector/rector-src` I always get erros like:

```
[ERROR] Call to undefined method                                                                                       
         "Symfony\Component\DependencyInjection\Loader\Configurator\ServiceConfigurator::configure()" in                
         /data/site/docroot/vendor/rector/rector-src/packages/Set/ValueObject/../../../config/set/code-quality.php      
         (which is being imported from "/data/site/docroot/rector.php").             
```

my current composer.json is like:

```
  "require": {
    "php": "^7.4 | ^8"
  },
  "require-dev": {
    "rector/rector-src": "dev-main",
    "rector/rector-generator": "dev-patch-1"
  },
```

Note: dev-patch-1 is the branch from #12 

Do you have any ideas what package is missing?

**Comment by TomasVotruba** [comment]
Hi, this package should be probably part of rector/rector. Could you move it to required dependencies there?

**Comment by wernerkrauss** [comment]
Thanks for your support!

You mean adding it to required of rector/rector?

When I try to install 

```
  "require": {
    "rector/rector": "^0.12",
    "rector/rector-generator": "dev-main"
  },
```

I get this error:

```
vendor/bin/rector init-recipe

                                                                                                                        
 [ERROR] Cannot autowire service "Rector\RectorGenerator\FileSystem\ConfigFilesystem": argument "$smartFileSystem" of   
         method "__construct()" references class "Symplify\SmartFileSystem\SmartFileSystem" but no such service exists. 
```

So you want me to make a PR with `rector-generate` as dependency of `rector/rector`? I don't understand the magic how that package is generated yet
 ;)

**Comment by TomasVotruba** [comment]
> So you want me to make a PR with rector-generate as dependency of rector/rector? 

That would be great 👍 

It should be available as part of Rector.

**Comment by wernerkrauss** [comment]
I don't understand, sorry. In [prefixed rector/rector,](https://github.com/rectorphp/rector/blob/main/composer.json) there are no composer dependencies to the different rector modules, but I see the code commited in vendor... The only references I see in the "conflicts" section...

Can you please explain to me how requirements are added to `rector/rector`?

**Comment by TomasVotruba** [comment]
The development repository is rector-src

**Comment by samsonasik** [comment]
should be resolved now, @wernerkrauss please try `"rector/rector": "dev-main"` to verify if it now working ok. 

```bash
composer config minimum-stability dev

composer config prefer-stable true

composer require --dev rector/rector:dev-main
```

**Comment by samsonasik** [comment]
@TomasVotruba I just tried it latest dev-main, it seems it got error:

```bash
 [ERROR] Class "Symplify\SymfonyPhpConfig\ValueObjectInliner" not found                                                 
```

on `generate`:

```bash
vendor/bin/rector init-recipe 

                                                                                                                        
 [OK] "rector-recipe.php" config file was added                                                                         
                                                                                                                        

vendor/bin/rector generate 

                                                                                                                        
 [ERROR] Class "Symplify\SymfonyPhpConfig\ValueObjectInliner" not found                                                                                                                                          
```

It seems `ValueObjectInliner` needs to removed from `templates`

https://github.com/rectorphp/rector-generator/blob/16d8c6bcc70e044604271fec9e1f1ca804265a54/templates/rector-recipe.php.dist#L79

**Comment by samsonasik** [comment]
Add `Symplify\SymfonyPhpConfig\*` seems not the solution as that will break breaks Symplify config downgrade ref https://github.com/rectorphp/rector-src/pull/1449/files#r766689713

**Comment by samsonasik** [comment]
@wernerkrauss @TomasVotruba I think the solution is to use `rector-src` instead, with the following steps:

```
composer config minimum-stability dev

composer config prefer-stable true

composer require --dev rector/rector-src

composer require --dev symplify/vendor-patches
```

After that, update your composer.json and add extra:

```
    "extra": {
        "enable-patching": true
    }
```

After that, run composer update: 

```
composer update
```

After that, require rector-generator:

```
composer require --dev rector/rector-generator:dev-main
```

And finally, run init-recipe and generate:

```bash
vendor/bin/rector init-recipe
vendor/bin/rector generate 
```

**Comment by samsonasik** [comment]
@wernerkrauss I created PR https://github.com/rectorphp/rector-generator/pull/14 for update documentation how to install it along with rector-src.

**Comment by TomasVotruba** [comment]
>  [ERROR] Class "Symplify\SymfonyPhpConfig\ValueObjectInliner" not found 

I see. The current workaround is needed, because of using value object in config. It's hacking Symfony, as it cannot handle value objects itself.
I came to similar errors and could not find the way around.

It might be worth to use only scalar values in `rector-recipe.php` and value object inside after the container is build.

**Comment by samsonasik** [comment]
@TomasVotruba thank you 👍 , I tried `"rector/rector": "dev-main"` and it seems working ok now:

```bash
mkdir test-init && cd test-init && yes | composer init --name some/test && composer config minimum-stability dev && composer require --dev rector/rector:dev-main && vendor/bin/rector init-recipe && vendor/bin/rector generate && cd .. && rm -rf test-init
Writing ./composer.json
./composer.json has been updated
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (dev-master 8ae4793)
  - Locking rector/rector (dev-main 891d788)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading phpstan/phpstan (dev-master 8ae4793)
  - Downloading rector/rector (dev-main 891d788)
  - Installing phpstan/phpstan (dev-master 8ae4793): Extracting archive
  - Installing rector/rector (dev-main 891d788): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

                                                                                                                        
 [OK] "rector-recipe.php" config file was added                                                                         
                                                                                                                        


New files generated for "RenameMethodCallRector":
=================================================

 * rules-tests/Naming/Rector/MethodCall/RenameMethodCallRector/Fixture/some_class.php.inc
 * rules-tests/Naming/Rector/MethodCall/RenameMethodCallRector/RenameMethodCallRectorTest.php
 * rules-tests/Naming/Rector/MethodCall/RenameMethodCallRector/config/configured_rule.php
 * rules/Naming/Rector/MethodCall/RenameMethodCallRector.php

                                                                                                                        
 [OK] Make tests green again:                                                                                           
                                                                                                                        
      vendor/bin/phpunit rules-tests/Naming/Rector/MethodCall/RenameMethodCallRector                                    
```

**Comment by TomasVotruba** [comment]
Awesome, thank you for verification :+1:

**Comment by wernerkrauss** [comment]
You guys rock! Thank you for helping me to start using rector. Now I can generate the first rules while I read the book with important background information. It works!

As a side note: should I make a PR that inlines [how to use rector generator in the docs](https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md#generating-a-rector-rule), as it's now part of rector/rector? Coming from that I thought I need to install the rector-generator package aside rector/rector which lead to this issue...

**Comment by samsonasik** [comment]
@wernerkrauss you can create PR into https://github.com/rectorphp/rector-src/blob/main/build/target-repository/docs/create_own_rule.md#generating-a-rector-rule as rector/rector is generated code.

**Comment by TomasVotruba** [comment]
Hi, thank you for feedback.
We improved the package a lot, thanks to you.

PR with little info would be great 👍
