### ISSUE TITLE
The readme could contain tips on autoloading :)

### ISSUE THREAD

**Issue by tarjei** [rectorphp/rector-generator#27]
Since the generator create rules and rules-tests in the root directory of the project and thus does not match the tips given in the book and the readme it would probably be a good idea to give some hints on how to configure autoloading.

**Comment by TomasVotruba** [comment]
Hi, 
thanks for suggetsion.
Could you propose a PR with such docs? We can review then :+1:

**Comment by TomasVotruba** [comment]
Closing as outdated. The autoloading and generator are completelly 2 different topics :slightly_smiling_face: 

Better check the docs of Rector itself: https://github.com/rectorphp/rector/tree/main/docs

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with docs improvements :+1:

Thank you for understanding :slightly_smiling_face:
