### ISSUE TITLE
How to install the rector-generator?

### ISSUE THREAD

**Issue by anyt** [rectorphp/rector-generator#34]
Hi, I required the package using composer, but it does not add the commands to the vendor/bin/rector. 
Maybe there are additional steps to make it work or I'm using it wrong. Thank you.

**Comment by TomasVotruba** [comment]
Hi, this package is for the core rules only, as it requires specific paths and namespace structure, e.g. src, tests e
tc.
For your custom package, it's easier to create rule copy-pasting previous one.
